export interface WordEntry { word: string; hint: string; }

export const WORD_BANK: Record<string, WordEntry[]> = {
  '💜 Love & Affection': [
    { word: 'FOREVER', hint: 'How long I want to be with you' },
    { word: 'SWEETHEART', hint: 'A loving nickname 💕' },
    { word: 'DEVOTION', hint: 'Deep love and loyalty' },
    { word: 'DARLING', hint: 'A word of endearment' },
    { word: 'CHERISH', hint: 'To hold something dearly' },
    { word: 'ADORE', hint: 'To love intensely' },
    { word: 'ROMANCE', hint: 'Love with butterflies ✨' },
    { word: 'TENDER', hint: 'Gentle and loving touch' },
    { word: 'PASSION', hint: 'Intense feeling of love' },
    { word: 'EMBRACE', hint: 'A warm hug 🤗' },
    { word: 'TREASURE', hint: 'Something precious to keep' },
    { word: 'BELOVED', hint: 'Dearly loved person' },
    { word: 'SOULMATE', hint: 'The person meant for you' },
    { word: 'AFFECTION', hint: 'Gentle fondness and care' },
    { word: 'HEARTBEAT', hint: 'The rhythm inside your chest 💓' },
    { word: 'CUDDLE', hint: 'Snuggle up close' },
    { word: 'WARMTH', hint: 'Cosy feeling of love' },
    { word: 'PROMISE', hint: 'A vow you keep forever' },
    { word: 'HARMONY', hint: 'Perfect peaceful balance' },
    { word: 'SERENITY', hint: 'Total peace and calm' },
    { word: 'EUPHORIA', hint: 'Extreme happiness and joy' },
    { word: 'ENCHANTED', hint: 'Under a magic love spell' },
    { word: 'RADIANT', hint: 'Glowing with happiness' },
    { word: 'TIMELESS', hint: 'Never grows old' },
    { word: 'INFINITY', hint: 'Going on and on forever' },
    { word: 'PARADISE', hint: 'A perfect place with you' },
    { word: 'WHISPER', hint: 'Soft words just between us' },
    { word: 'PRECIOUS', hint: 'Invaluable and dear' },
    { word: 'FAITHFUL', hint: 'Always loyal and true' },
    { word: 'SINCERE', hint: 'Honest and genuine feelings' },
    { word: 'HONEYMOON', hint: 'Romantic trip after wedding 🌙' },
    { word: 'WEDDING', hint: 'The day of forever 💍' },
    { word: 'PROPOSAL', hint: 'Getting down on one knee 💍' },
    { word: 'BLISSFUL', hint: 'Perfectly happy and content' },
    { word: 'LOYAL', hint: 'Always by your side' },
    { word: 'COMFORT', hint: 'Ease in troubled times' },
    { word: 'MISSING', hint: 'When distance hurts' },
    { word: 'LONGING', hint: 'Yearning for someone far away' },
    { word: 'DEAREST', hint: 'Most loved of all' },
    { word: 'BLOSSOM', hint: 'Love growing like a flower 🌸' },
    { word: 'MAGICAL', hint: 'Impossibly wonderful feeling' },
    { word: 'GENUINE', hint: 'Real, authentic love' },
    { word: 'ABSOLUTE', hint: 'Complete and total love' },
    { word: 'MOONLIGHT', hint: 'Romantic glow on a quiet night 🌙' },
    { word: 'STARDUST', hint: 'We are all made of it ✨' },
    { word: 'DARLING', hint: 'An endearing name for a loved one' },
    { word: 'DEVOTION', hint: 'Unwavering deep commitment' },
    { word: 'ROMANTIC', hint: 'Full of love and feeling' },
    { word: 'HEARTFELT', hint: 'Coming from deep inside the heart' },
    { word: 'CHERISHED', hint: 'Held so dear to the heart' },
  ],
  '🐾 Cute Animals': [
    { word: 'KITTEN', hint: 'A baby cat 🐱' },
    { word: 'PUPPY', hint: 'A baby dog 🐶' },
    { word: 'PANDA', hint: 'Black and white bear that loves bamboo' },
    { word: 'BUNNY', hint: 'Fluffy ears and a cottontail 🐰' },
    { word: 'KOALA', hint: 'Australian tree-hugger 🌿' },
    { word: 'PENGUIN', hint: 'Tuxedo bird from the south pole 🐧' },
    { word: 'HAMSTER', hint: 'Chubby cheeks, loves wheels 🐹' },
    { word: 'DUCKLING', hint: 'A baby duck who follows mama 🐥' },
    { word: 'HEDGEHOG', hint: 'Spiny little creature that rolls up' },
    { word: 'FERRET', hint: 'Long slinky playful mammal' },
    { word: 'CHINCHILLA', hint: 'Super soft fur from South America' },
    { word: 'CAPYBARA', hint: 'World\'s largest rodent, very chill' },
    { word: 'AXOLOTL', hint: 'Smiling water dragon salamander' },
    { word: 'JELLYFISH', hint: 'Glowing sea creature with tentacles 🌊' },
    { word: 'FLAMINGO', hint: 'Pink bird that stands on one leg 🦩' },
    { word: 'TOUCAN', hint: 'Tropical bird with huge colourful beak' },
    { word: 'MEERKAT', hint: 'Desert guard that stands upright' },
    { word: 'OTTER', hint: 'Holds hands while sleeping 🦦' },
    { word: 'NARWHAL', hint: 'Unicorn of the sea 🌊' },
    { word: 'PLATYPUS', hint: 'Beak + fur + lays eggs = surprise!' },
    { word: 'SEAHORSE', hint: 'Tiny ocean creature, dad gives birth' },
    { word: 'BUTTERFLY', hint: 'Starts as a caterpillar 🦋' },
    { word: 'DRAGONFLY', hint: 'Shimmery-winged insect near ponds' },
    { word: 'BUMBLEBEE', hint: 'Stripy fuzzy pollinator 🐝' },
    { word: 'PORCUPINE', hint: 'Sharp quill-covered rodent' },
    { word: 'ALPACA', hint: 'Fluffy South American camel cousin 🦙' },
    { word: 'MANATEE', hint: 'Gentle sea cow 🌊' },
    { word: 'SLOTH', hint: 'World\'s slowest mammal 🌿' },
    { word: 'CHAMELEON', hint: 'Changes colour to match surroundings' },
    { word: 'PARROT', hint: 'Colourful bird that talks 🦜' },
    { word: 'CORGI', hint: 'Queen\'s short-legged dog 🐾' },
    { word: 'BEAGLE', hint: 'Floppy-eared sniffing dog' },
    { word: 'DACHSHUND', hint: 'Long sausage-shaped doggo 🐕' },
    { word: 'POMERANIAN', hint: 'Tiny fluffy dog like a cotton ball' },
    { word: 'SIAMESE', hint: 'Blue-eyed elegant cat breed' },
    { word: 'RAGDOLL', hint: 'Floppy gentle giant cat breed' },
    { word: 'SAMOYED', hint: 'White fluffy smiling sled dog' },
    { word: 'GECKO', hint: 'Wall-climbing tropical lizard' },
    { word: 'FIREFLY', hint: 'Glows in the dark at night ✨' },
    { word: 'LADYBUG', hint: 'Red beetle with black spots 🐞' },
    { word: 'CANARY', hint: 'Tiny bright yellow singing bird' },
    { word: 'PEACOCK', hint: 'Magnificent tail of feathers 🦚' },
    { word: 'LEMUR', hint: 'Big-eyed primate from Madagascar' },
    { word: 'WOMBAT', hint: 'Cube-poop producing Australian marsupial' },
    { word: 'QUOKKA', hint: 'World\'s happiest smiling animal 😊' },
    { word: 'TAPIR', hint: 'Pig-elephant hybrid-looking animal' },
    { word: 'MANDRILL', hint: 'Colourful-faced baboon' },
    { word: 'NUMBAT', hint: 'Stripy Australian anteater' },
    { word: 'OKAPI', hint: 'Zebra-striped cousin of the giraffe' },
    { word: 'KINKAJOU', hint: 'Honey-bear of the rainforest' },
  ],
  '🍓 Sweet Treats': [
    { word: 'CHOCOLATE', hint: 'Sweet dark melts in your mouth 🍫' },
    { word: 'CUPCAKE', hint: 'Tiny frosted cake 🧁' },
    { word: 'STRAWBERRY', hint: 'Red heart-shaped fruit 🍓' },
    { word: 'HONEY', hint: 'Sweet stuff bees make 🍯' },
    { word: 'CARAMEL', hint: 'Sticky golden sweetness' },
    { word: 'MOCHI', hint: 'Soft Japanese sweet rice cake' },
    { word: 'TRUFFLE', hint: 'Fancy chocolate ball 🍬' },
    { word: 'MACARON', hint: 'Colourful French sandwich cookie' },
    { word: 'TIRAMISU', hint: 'Italian coffee cream dessert 🍮' },
    { word: 'CHURROS', hint: 'Spanish fried dough with cinnamon' },
    { word: 'WAFFLE', hint: 'Grid-patterned breakfast treat 🧇' },
    { word: 'BROWNIE', hint: 'Fudgy chocolate square bake' },
    { word: 'CHEESECAKE', hint: 'Creamy cake on biscuit base' },
    { word: 'PANCAKE', hint: 'Flat fluffy breakfast with syrup 🥞' },
    { word: 'CROISSANT', hint: 'Flaky buttery French pastry 🥐' },
    { word: 'BEIGNET', hint: 'New Orleans powdered sugar fritter' },
    { word: 'PRALINE', hint: 'Caramelised nut confection' },
    { word: 'ECLAIR', hint: 'Chocolate-topped custard finger pastry' },
    { word: 'CANNOLI', hint: 'Italian pastry tube with cream' },
    { word: 'GELATO', hint: 'Italian-style creamy ice cream 🍦' },
    { word: 'SORBET', hint: 'Fruity frozen dessert without cream' },
    { word: 'MERINGUE', hint: 'Light crispy beaten egg white' },
    { word: 'PAVLOVA', hint: 'Meringue base with cream and fruit' },
    { word: 'BAKLAVA', hint: 'Middle Eastern honey nut pastry' },
    { word: 'TOFFEE', hint: 'Hard chewy caramel candy' },
    { word: 'FUDGE', hint: 'Soft sweet chocolatey block' },
    { word: 'BUTTERSCOTCH', hint: 'Warm buttery caramel flavour' },
    { word: 'MARSHMALLOW', hint: 'Soft pillowy white candy ☁️' },
    { word: 'LOLLIPOP', hint: 'Candy on a stick 🍭' },
    { word: 'SHERBET', hint: 'Fizzy fruit-flavoured powder candy' },
    { word: 'FONDANT', hint: 'Smooth sugar paste for cakes' },
    { word: 'GANACHE', hint: 'Rich chocolate cream mixture' },
    { word: 'PROFITEROLE', hint: 'Cream-filled choux pastry ball' },
    { word: 'KULFI', hint: 'Indian dense creamy ice cream' },
    { word: 'HALVA', hint: 'Middle Eastern sesame sweet' },
    { word: 'NOUGAT', hint: 'Chewy nut-filled candy bar' },
    { word: 'PEPPERMINT', hint: 'Cool minty candy flavour' },
    { word: 'LADOO', hint: 'Round Indian sweet ball 🟡' },
    { word: 'BONBON', hint: 'Small decorated chocolate piece' },
    { word: 'MADELEINE', hint: 'Shell-shaped French sponge cake' },
    { word: 'CINNAMON', hint: 'Warm spice used in sweet treats' },
    { word: 'TRIFLE', hint: 'Layered British dessert in a bowl' },
    { word: 'JALEBI', hint: 'Spiral Indian syrup-soaked sweet' },
    { word: 'CHURRO', hint: 'Long fried dough stick with cinnamon' },
    { word: 'TAPIOCA', hint: 'Chewy pearls in bubble tea 🧋' },
    { word: 'PASSIONFRUIT', hint: 'Tart tropical wrinkled fruit' },
    { word: 'GUAVA', hint: 'Pink-fleshed tropical sweet fruit' },
    { word: 'LYCHEE', hint: 'Small Asian fruit with sweet flesh' },
    { word: 'COCONUT', hint: 'Tropical hairy-shelled white fruit 🥥' },
    { word: 'PAPAYA', hint: 'Orange tropical fruit from the tropics' },
  ],
  '🌟 Dreams & Memories': [
    { word: 'LAUGHTER', hint: 'The best sound in the world 😂' },
    { word: 'FUTURE', hint: 'Where we are going together ✨' },
    { word: 'ADVENTURE', hint: 'An exciting journey together 🗺️' },
    { word: 'SUNRISE', hint: 'A beautiful beginning 🌅' },
    { word: 'JOURNEY', hint: 'Life is one big one 🛤️' },
    { word: 'MEMORY', hint: 'A moment kept in your heart 💭' },
    { word: 'MAGIC', hint: 'What we have together ✨' },
    { word: 'WONDER', hint: 'The feeling of awe and amazement' },
    { word: 'NOSTALGIA', hint: 'Bittersweet longing for the past' },
    { word: 'DREAMING', hint: 'What sleep and hope are made of 💭' },
    { word: 'MILESTONE', hint: 'An important life achievement' },
    { word: 'FIREWORKS', hint: 'Explosive celebration in the sky 🎆' },
    { word: 'CHILDHOOD', hint: 'The early years of life 🧸' },
    { word: 'REUNION', hint: 'Meeting again after time apart' },
    { word: 'LULLABY', hint: 'A soothing bedtime song 🎵' },
    { word: 'VINTAGE', hint: 'Old but beautiful with age' },
    { word: 'TWILIGHT', hint: 'Soft light between day and night 🌆' },
    { word: 'MOONLIGHT', hint: 'Gentle glow on a quiet night 🌙' },
    { word: 'STARGAZING', hint: 'Looking up at the night sky 🌟' },
    { word: 'LEGACY', hint: 'What you leave behind forever' },
    { word: 'BIRTHDAY', hint: 'Your special day every year 🎂' },
    { word: 'ANNIVERSARY', hint: 'Celebrating a year together 🎊' },
    { word: 'PHOTOGRAPH', hint: 'A frozen moment in time 📷' },
    { word: 'SENTIMENTAL', hint: 'Attached to emotions and memories' },
    { word: 'REMINISCE', hint: 'To think fondly of the past' },
    { word: 'KEEPSAKE', hint: 'A token you hold onto forever' },
    { word: 'CHAPTERS', hint: 'Parts of the story of your life' },
    { word: 'BELONGING', hint: 'The feeling of being home 🏡' },
    { word: 'SANCTUARY', hint: 'A safe place of comfort' },
    { word: 'GRATITUDE', hint: 'Thankfulness in your heart' },
    { word: 'INFINITE', hint: 'Without end, like our love ♾️' },
    { word: 'REVERIE', hint: 'A pleasant daydream state' },
    { word: 'LOCKET', hint: 'Tiny photo held in a pendant necklace' },
    { word: 'HOURGLASS', hint: 'Time slipping through your fingers ⌛' },
    { word: 'WANDERING', hint: 'Exploring without a fixed direction' },
    { word: 'PEACEFUL', hint: 'Calm and without worry' },
    { word: 'TIMELESS', hint: 'Never fading, always beautiful' },
    { word: 'CHRONICLE', hint: 'A record of events over time' },
    { word: 'ECLIPSE', hint: 'Sun or moon blocked — rare moment 🌑' },
    { word: 'CELESTIAL', hint: 'Relating to the sky and heavens ⭐' },
    { word: 'SHOOTING STAR', hint: 'A meteor streaking across the sky' },
    { word: 'DUSK', hint: 'The quiet time just after sunset' },
    { word: 'FIRSTS', hint: 'The beginning of something special' },
    { word: 'CHERISHED', hint: 'Held dearly in the heart always' },
  ],
  '🌍 Countries & Places': [
    { word: 'LONDON', hint: 'Capital of England with Big Ben 🇬🇧' },
    { word: 'PARIS', hint: 'City of love and the Eiffel Tower 🗼' },
    { word: 'TOKYO', hint: 'Bustling capital of Japan 🇯🇵' },
    { word: 'COLOMBO', hint: 'Capital of Sri Lanka 🇱🇰' },
    { word: 'MALDIVES', hint: 'Island paradise in the Indian Ocean 🌊' },
    { word: 'SANTORINI', hint: 'White-domed beautiful Greek island' },
    { word: 'BALI', hint: 'Tropical island paradise in Indonesia 🌺' },
    { word: 'BANGKOK', hint: 'Vibrant capital of Thailand 🇹🇭' },
    { word: 'SINGAPORE', hint: 'City-state in Southeast Asia 🦁' },
    { word: 'SYDNEY', hint: 'Australian city with famous Opera House' },
    { word: 'BARCELONA', hint: 'Gaudi\'s colourful Spanish city' },
    { word: 'ROME', hint: 'The Eternal City with the Colosseum 🏛️' },
    { word: 'AMSTERDAM', hint: 'Dutch city of canals and tulips 🌷' },
    { word: 'VIENNA', hint: 'City of music and pastries 🎵' },
    { word: 'PRAGUE', hint: 'Fairy-tale city in Czech Republic' },
    { word: 'ISTANBUL', hint: 'Where Europe meets Asia 🕌' },
    { word: 'DUBAI', hint: 'Gleaming skyscraper city in UAE 🇦🇪' },
    { word: 'MARRAKECH', hint: 'Colourful city in Morocco 🇲🇦' },
    { word: 'VENICE', hint: 'Italian city built on water 🇮🇹' },
    { word: 'FLORENCE', hint: 'Renaissance art capital of Italy' },
    { word: 'REYKJAVIK', hint: 'Capital near the Northern Lights in Iceland' },
    { word: 'EDINBURGH', hint: 'Scottish capital with a famous castle 🏰' },
    { word: 'LISBON', hint: 'Hilly capital of Portugal with trams' },
    { word: 'BUDAPEST', hint: 'Twin city on the Danube in Hungary' },
    { word: 'KYOTO', hint: 'Ancient Japanese city of temples 🏯' },
    { word: 'SEOUL', hint: 'Neon-lit capital of South Korea' },
    { word: 'HAVANA', hint: 'Cuban capital of vintage cars and music' },
    { word: 'CAIRO', hint: 'Egyptian city near the Pyramids 🐪' },
    { word: 'PETRA', hint: 'Ancient rose-red city carved in Jordan' },
    { word: 'SIGIRIYA', hint: 'Ancient rock fortress in Sri Lanka 🦁' },
    { word: 'KANDY', hint: 'Sri Lankan city with the Tooth Temple' },
    { word: 'ELLA', hint: 'Beautiful hill country in Sri Lanka 🌿' },
    { word: 'GALLE', hint: 'Sri Lankan fort city by the sea' },
    { word: 'CAPETOWN', hint: 'South African city at the tip of land' },
    { word: 'AUCKLAND', hint: 'Largest city in New Zealand' },
    { word: 'NAIROBI', hint: 'Capital city of Kenya 🦁' },
    { word: 'HANOI', hint: 'Capital of Vietnam 🇻🇳' },
    { word: 'ALASKA', hint: 'US state with glaciers and bears 🐻' },
    { word: 'PATAGONIA', hint: 'Wild southernmost region of the world' },
    { word: 'AMALFI', hint: 'Stunning Italian cliff-side coast' },
    { word: 'PORTO', hint: 'Portuguese city famous for wine' },
    { word: 'TBILISI', hint: 'Ancient capital of Georgia' },
    { word: 'QUEENSTOWN', hint: 'New Zealand adventure capital' },
    { word: 'ZANZIBAR', hint: 'Spice island paradise off Tanzania' },
  ],
  '🎬 Movies & Shows': [
    { word: 'TITANIC', hint: 'Tragic love story on a doomed ship 🚢' },
    { word: 'AVATAR', hint: 'Blue aliens on planet Pandora' },
    { word: 'FROZEN', hint: 'Let it go in an icy kingdom ❄️' },
    { word: 'INCEPTION', hint: 'Dream within a dream 💭' },
    { word: 'INTERSTELLAR', hint: 'Father crosses galaxies for love 🌌' },
    { word: 'PARASITE', hint: 'Korean Oscar-winning thriller' },
    { word: 'RATATOUILLE', hint: 'Rat who loves to cook in Paris 🐀' },
    { word: 'COCO', hint: 'Pixar story about Mexican ancestors 🎸' },
    { word: 'SHREK', hint: 'Ogre who falls for Princess Fiona' },
    { word: 'ALADDIN', hint: 'Magic lamp and flying carpet 🪔' },
    { word: 'MOANA', hint: 'Polynesian girl who finds the ocean' },
    { word: 'SPIRITED AWAY', hint: 'Miyazaki\'s spirit world masterpiece' },
    { word: 'BRIDGERTON', hint: 'Regency-era romance on Netflix' },
    { word: 'EUPHORIA', hint: 'Glittery teen drama series' },
    { word: 'FRIENDS', hint: '6 New Yorkers on a coffee-shop couch ☕' },
    { word: 'STRANGER THINGS', hint: 'Upside Down mystery in the 80s' },
    { word: 'SQUID GAME', hint: 'Korean survival show with childhood games' },
    { word: 'WEDNESDAY', hint: 'Gloomy Addams girl at magic school' },
    { word: 'BARBIE', hint: 'Pink world meets real world 💗' },
    { word: 'OPPENHEIMER', hint: 'Atomic bomb creator biopic 💥' },
    { word: 'DUNE', hint: 'Sand planet and spice sci-fi epic' },
    { word: 'TOPGUN', hint: 'Maverick pilot in action sequel ✈️' },
    { word: 'WHIPLASH', hint: 'Jazz drummer pushed to the limits 🥁' },
    { word: 'SOUL', hint: 'Pixar film about finding your purpose 🎵' },
    { word: 'ENCANTO', hint: 'Colombian magical family story 🦋' },
    { word: 'TENET', hint: 'Nolan\'s time inversion thriller' },
    { word: 'ARRIVAL', hint: 'Linguist decodes alien language 🛸' },
    { word: 'CASABLANCA', hint: 'Classic wartime romance film' },
    { word: 'GRAVITY', hint: 'Astronaut stranded alone in space 🌌' },
    { word: 'PRIDE', hint: 'Darcy and Elizabeth\'s slow burn 💕' },
    { word: 'SUCCESSION', hint: 'Rich family power struggle drama' },
    { word: 'OUTLANDER', hint: 'Time-travel Scottish romance series' },
    { word: 'SHOGUN', hint: 'Epic Japanese samurai period drama' },
    { word: 'HEARTSTOPPER', hint: 'Sweet teen graphic novel show 💚' },
    { word: 'BLACKMIRROR', hint: 'Dark tech anthology series 📱' },
    { word: 'GAMEOFTHRONES', hint: 'Winter is coming and dragons roar 🐉' },
    { word: 'BREAKING BAD', hint: 'Chemistry teacher goes dangerous' },
    { word: 'LUCA', hint: 'Pixar sea monster in an Italian summer' },
    { word: 'FELLOWSHIP', hint: 'First Lord of the Rings chapter 💍' },
    { word: 'NOTEBOOK', hint: 'Rain kiss love story 🌧️' },
    { word: 'CINDERELLA', hint: 'Glass slipper fairy tale 👠' },
    { word: 'HOGWARTS', hint: 'School of witchcraft and wizardry 🧙' },
    { word: 'MIDNIGHT', hint: '... in Paris, Woody Allen romance' },
    { word: 'VERTIGO', hint: 'Hitchcock\'s classic thriller 🌀' },
  ],
  '🎵 Music & Songs': [
    { word: 'MELODY', hint: 'A sequence of musical notes 🎵' },
    { word: 'HARMONY', hint: 'Notes blending beautifully together' },
    { word: 'SYMPHONY', hint: 'A large orchestral composition' },
    { word: 'SERENADE', hint: 'A love song performed outside' },
    { word: 'LULLABY', hint: 'Song to send someone to sleep 🌙' },
    { word: 'CHORUS', hint: 'The repeated part of a song 🎤' },
    { word: 'CRESCENDO', hint: 'Music gradually getting louder' },
    { word: 'ACOUSTIC', hint: 'Natural sound without electronics 🎸' },
    { word: 'BEATLES', hint: 'Fab Four from Liverpool 🎸' },
    { word: 'BEYONCE', hint: 'Queen B putting a ring on it 👑' },
    { word: 'COLDPLAY', hint: 'Fix You and Yellow band 🌟' },
    { word: 'SHEERAN', hint: 'Ed, Shape of You singer 🎸' },
    { word: 'RIHANNA', hint: 'Umbrella singer and beauty mogul ☂️' },
    { word: 'IMAGINE', hint: 'John Lennon\'s iconic peace anthem' },
    { word: 'THRILLER', hint: 'Michael Jackson horror bop 🕺' },
    { word: 'BOHEMIAN', hint: '... Rhapsody by Queen 👑' },
    { word: 'JAZZ', hint: 'Improvisational American music genre 🎷' },
    { word: 'BLUES', hint: 'Soulful American musical roots' },
    { word: 'REGGAE', hint: 'Jamaican rhythm with Bob Marley 🇯🇲' },
    { word: 'CLASSICAL', hint: 'Bach, Mozart, Beethoven era 🎹' },
    { word: 'FLAMENCO', hint: 'Passionate Spanish guitar dance music' },
    { word: 'ORCHESTRA', hint: 'Large group of musicians 🎻' },
    { word: 'SOPRANO', hint: 'Highest classical singing voice' },
    { word: 'PIANO', hint: 'Black and white keys instrument 🎹' },
    { word: 'SAXOPHONE', hint: 'Jazzy metal woodwind instrument 🎷' },
    { word: 'DRUMS', hint: 'Percussion instrument you bash 🥁' },
    { word: 'VINYL', hint: 'Old-school record disc 🎵' },
    { word: 'KARAOKE', hint: 'Singing along to lyrics on screen 🎤' },
    { word: 'CONCERT', hint: 'Live music performance event 🎤' },
    { word: 'FESTIVAL', hint: 'Outdoor music event in a field 🎪' },
    { word: 'HALLELUJAH', hint: 'Leonard Cohen\'s sacred song' },
    { word: 'WONDERWALL', hint: 'Oasis 90s classic anthem' },
    { word: 'PURPLE RAIN', hint: 'Prince\'s iconic sad ballad' },
    { word: 'STAIRWAY', hint: '... to Heaven by Led Zeppelin' },
    { word: 'PLAYLIST', hint: 'A curated list of songs' },
    { word: 'BACKSTAGE', hint: 'Behind the performance curtain' },
    { word: 'DEBUT', hint: 'An artist\'s first album or show' },
    { word: 'ENCORE', hint: 'Extra performance after the show 🎉' },
    { word: 'BALLAD', hint: 'A slow emotional love song' },
    { word: 'TEMPO', hint: 'The speed of a piece of music' },
    { word: 'RHYTHM', hint: 'The beat pattern in music' },
    { word: 'LYRICS', hint: 'The words of a song' },
    { word: 'BASSLINE', hint: 'Deep low musical foundation' },
    { word: 'REFRAIN', hint: 'The repeated section of a song' },
  ],
  '🌺 Nature & Weather': [
    { word: 'RAINBOW', hint: 'Colourful arc after rain 🌈' },
    { word: 'THUNDER', hint: 'Loud crash during a storm ⛈️' },
    { word: 'BLOSSOM', hint: 'Flowers blooming on a tree 🌸' },
    { word: 'WATERFALL', hint: 'Water cascading down rocks 💦' },
    { word: 'GLACIER', hint: 'Slow-moving river of ice 🧊' },
    { word: 'VOLCANO', hint: 'Mountain that erupts lava 🌋' },
    { word: 'AURORA', hint: 'Northern or Southern Lights 🌌' },
    { word: 'TORNADO', hint: 'Spinning funnel of wind 🌪️' },
    { word: 'BLIZZARD', hint: 'Heavy snowstorm with strong winds ❄️' },
    { word: 'MONSOON', hint: 'Seasonal heavy rainfall season 🌧️' },
    { word: 'TROPICAL', hint: 'Hot and humid near the equator 🌴' },
    { word: 'MEADOW', hint: 'Open grassy field of flowers 🌼' },
    { word: 'JUNGLE', hint: 'Dense tropical forest 🌿' },
    { word: 'TUNDRA', hint: 'Frozen treeless Arctic plain' },
    { word: 'SAVANNAH', hint: 'African grassland with acacia trees 🦒' },
    { word: 'LAGOON', hint: 'Shallow body of water near the sea' },
    { word: 'EQUINOX', hint: 'Day and night are equal length' },
    { word: 'SOLSTICE', hint: 'Longest or shortest day of the year' },
    { word: 'ECLIPSE', hint: 'Sun blocked by the moon 🌑' },
    { word: 'MOONRISE', hint: 'Moon appearing above the horizon 🌕' },
    { word: 'DEWDROP', hint: 'Tiny water droplet on morning grass' },
    { word: 'LAVENDER', hint: 'Purple fragrant French flower 💜' },
    { word: 'JASMINE', hint: 'White fragrant climbing flower' },
    { word: 'LOTUS', hint: 'Sacred flower that grows in mud 🌸' },
    { word: 'SUNFLOWER', hint: 'Tall yellow flower that follows the sun 🌻' },
    { word: 'WILLOW', hint: 'Weeping drooping graceful tree' },
    { word: 'BAMBOO', hint: 'Fast-growing grass loved by pandas 🐼' },
    { word: 'AMETHYST', hint: 'Purple crystal gemstone 💜' },
    { word: 'SAPPHIRE', hint: 'Deep blue precious gemstone 💎' },
    { word: 'EMERALD', hint: 'Rich green precious gemstone 💚' },
    { word: 'PEARL', hint: 'White gem made inside an oyster' },
    { word: 'SNOWFLAKE', hint: 'No two are exactly alike ❄️' },
    { word: 'PETRICHOR', hint: 'The smell of rain on dry earth' },
    { word: 'ZEPHYR', hint: 'A gentle warm summer breeze 🌬️' },
    { word: 'CHERRY', hint: 'Blossom tree in spring Japan 🌸' },
    { word: 'PEBBLE', hint: 'Smooth small stone by the river' },
    { word: 'FERN', hint: 'Ancient leafy green plant 🌿' },
    { word: 'OBSIDIAN', hint: 'Black volcanic glass rock' },
    { word: 'PENINSULA', hint: 'Land surrounded by water on 3 sides' },
    { word: 'ARCHIPELAGO', hint: 'Chain of islands in the ocean' },
    { word: 'MANGROVE', hint: 'Tree with roots in salty water' },
    { word: 'CORAL', hint: 'Ocean rainbow underwater garden 🐠' },
    { word: 'LIGHTNING', hint: 'Electric flash in a storm ⚡' },
    { word: 'CYCLONE', hint: 'Rotating tropical storm system' },
  ],
  '🍕 Food & Drinks': [
    { word: 'SUSHI', hint: 'Japanese rice rolls 🍱' },
    { word: 'RAMEN', hint: 'Japanese noodle soup 🍜' },
    { word: 'PIZZA', hint: 'Italian flat bread with toppings 🍕' },
    { word: 'PASTA', hint: 'Italian wheat noodles 🍝' },
    { word: 'BURGER', hint: 'Stacked bun with patty 🍔' },
    { word: 'TACOS', hint: 'Mexican folded tortillas 🌮' },
    { word: 'BIRYANI', hint: 'Fragrant South Asian spiced rice dish' },
    { word: 'CURRY', hint: 'Spiced sauce dish from South Asia 🍛' },
    { word: 'DUMPLINGS', hint: 'Filled dough pockets 🥟' },
    { word: 'PAELLA', hint: 'Spanish saffron rice dish 🥘' },
    { word: 'HUMMUS', hint: 'Middle Eastern chickpea dip 🫙' },
    { word: 'FALAFEL', hint: 'Deep-fried spiced chickpea ball 🧆' },
    { word: 'SHAWARMA', hint: 'Middle Eastern meat wrap 🌯' },
    { word: 'AVOCADO', hint: 'Green fruit loved on toast 🥑' },
    { word: 'MANGO', hint: 'Tropical sweet orange fruit 🥭' },
    { word: 'PINEAPPLE', hint: 'Spiky tropical yellow fruit 🍍' },
    { word: 'MATCHA', hint: 'Japanese green tea powder 🍵' },
    { word: 'ESPRESSO', hint: 'Strong Italian coffee shot ☕' },
    { word: 'BUBBLE TEA', hint: 'Taiwanese drink with tapioca pearls 🧋' },
    { word: 'SMOOTHIE', hint: 'Blended fruit drink in a glass 🍹' },
    { word: 'CHAMPAGNE', hint: 'Bubbly French celebration drink 🥂' },
    { word: 'KIMCHI', hint: 'Korean fermented spicy cabbage' },
    { word: 'TEMPURA', hint: 'Japanese deep-fried battered food' },
    { word: 'GYOZA', hint: 'Japanese pan-fried dumplings 🥟' },
    { word: 'BRUSCHETTA', hint: 'Italian grilled tomato bread starter' },
    { word: 'FONDUE', hint: 'Swiss melted cheese dipping dish 🫕' },
    { word: 'RISOTTO', hint: 'Creamy Italian rice dish 🍚' },
    { word: 'TAPAS', hint: 'Spanish small sharing plates 🥘' },
    { word: 'NAAN', hint: 'Soft pillowy Indian flatbread' },
    { word: 'MISO', hint: 'Japanese fermented soybean paste soup 🍵' },
    { word: 'STROGANOFF', hint: 'Russian beef in cream sauce dish' },
    { word: 'LEMONADE', hint: 'Tart cold citrus summer drink 🍋' },
    { word: 'SANGRIA', hint: 'Spanish red wine and fruit punch' },
    { word: 'MOCKTAIL', hint: 'A fancy cocktail without alcohol 🍹' },
    { word: 'PIEROGI', hint: 'Polish stuffed dumplings 🥟' },
    { word: 'JOLLOF', hint: 'West African one-pot rice dish 🍚' },
    { word: 'GAZPACHO', hint: 'Cold Spanish tomato soup 🍅' },
    { word: 'PHO', hint: 'Vietnamese fragrant noodle soup 🍜' },
    { word: 'CROISSANT', hint: 'Flaky buttery French breakfast 🥐' },
    { word: 'DURIAN', hint: 'Stinky king of tropical fruits 👑' },
    { word: 'LYCHEE', hint: 'Small pink tropical fruit from Asia' },
    { word: 'GNOCCHI', hint: 'Italian soft potato dumplings' },
    { word: 'INJERA', hint: 'Ethiopian spongy sourdough flatbread' },
    { word: 'TIRAMISU', hint: 'Italian coffee mascarpone dessert ☕' },
  ],
  '🎮 Games & Hobbies': [
    { word: 'MINECRAFT', hint: 'Build anything in a block world 🧱' },
    { word: 'POKEMON', hint: 'Gotta catch them all! 🎮' },
    { word: 'CHESS', hint: 'Strategy board game of kings ♟️' },
    { word: 'SCRABBLE', hint: 'Make words from letter tiles 🔤' },
    { word: 'MONOPOLY', hint: 'Buy properties, bankrupt your friends 🎲' },
    { word: 'JENGA', hint: 'Pull blocks without toppling the tower' },
    { word: 'ORIGAMI', hint: 'Japanese art of paper folding 📄' },
    { word: 'KNITTING', hint: 'Making fabric with two needles 🧶' },
    { word: 'POTTERY', hint: 'Shaping clay on a spinning wheel 🏺' },
    { word: 'SKETCHING', hint: 'Drawing with pencil and paper 🎨' },
    { word: 'GARDENING', hint: 'Growing plants and flowers 🌷' },
    { word: 'BAKING', hint: 'Making treats in the oven 🧁' },
    { word: 'JOURNALING', hint: 'Writing thoughts in a diary 📓' },
    { word: 'PHOTOGRAPHY', hint: 'Capturing moments with a camera 📷' },
    { word: 'STARGAZING', hint: 'Watching the night sky through a lens 🔭' },
    { word: 'YOGA', hint: 'Stretching and breathing mindfully 🧘' },
    { word: 'DANCING', hint: 'Moving to music gracefully 💃' },
    { word: 'COOKING', hint: 'Making food from scratch 👨‍🍳' },
    { word: 'HIKING', hint: 'Walking through nature trails 🥾' },
    { word: 'CYCLING', hint: 'Riding a bicycle on roads or trails 🚴' },
    { word: 'SURFING', hint: 'Riding waves on a board 🏄' },
    { word: 'CLIMBING', hint: 'Scaling a rock face or wall 🧗' },
    { word: 'ARCHERY', hint: 'Shooting arrows at a target 🏹' },
    { word: 'COSPLAY', hint: 'Dressing as your favourite character' },
    { word: 'EMBROIDERY', hint: 'Decorative needle and thread art 🪡' },
    { word: 'CALLIGRAPHY', hint: 'Beautiful decorative handwriting' },
    { word: 'CROCHETING', hint: 'Hooking yarn into patterns and shapes' },
    { word: 'SCRAPBOOK', hint: 'Photo and memory collage book' },
    { word: 'PAINTING', hint: 'Creating art with brushes 🖌️' },
    { word: 'MEDITATION', hint: 'Quiet mindful practice 🧘' },
    { word: 'PUZZLE', hint: 'Fitting many pieces together 🧩' },
    { word: 'KARAOKE', hint: 'Singing along with on-screen lyrics 🎤' },
    { word: 'ANIMATION', hint: 'Making drawings come to life 🎬' },
    { word: 'MARATHON', hint: '26.2 mile running race 🏃' },
    { word: 'SWIMMING', hint: 'Moving through water with strokes 🏊' },
    { word: 'TABLETOP', hint: 'Playing games around a table with friends' },
    { word: 'BOOK CLUB', hint: 'Group that reads and discusses books 📚' },
    { word: 'VOLUNTEERING', hint: 'Giving time to help others 💚' },
    { word: 'PODCAST', hint: 'Recorded audio show 🎙️' },
    { word: 'CHARADES', hint: 'Act it out without speaking at all' },
    { word: 'PICTIONARY', hint: 'Draw clues for your team to guess ✏️' },
    { word: 'PARAGLIDING', hint: 'Gliding with a parachute wing 🪂' },
    { word: 'KAYAKING', hint: 'Paddling a small boat on water 🚣' },
    { word: 'SNORKELING', hint: 'Swimming face-down to see the reef 🐠' },
  ],
  '👗 Fashion & Beauty': [
    { word: 'VELVET', hint: 'Soft luxurious plush fabric 💜' },
    { word: 'CASHMERE', hint: 'Incredibly soft wool from mountain goats' },
    { word: 'SEQUIN', hint: 'Shiny decorative disc on clothing ✨' },
    { word: 'CHIFFON', hint: 'Light sheer flowing delicate fabric' },
    { word: 'COUTURE', hint: 'High-end custom-made fashion 👗' },
    { word: 'VINTAGE', hint: 'Classic fashion from past decades' },
    { word: 'BOHEMIAN', hint: 'Free-spirited flowy fashion style' },
    { word: 'MINIMALIST', hint: 'Clean simple less-is-more style' },
    { word: 'PASTEL', hint: 'Soft light washed-out pretty colours' },
    { word: 'STILETTO', hint: 'Tall thin-heeled elegant shoe 👠' },
    { word: 'LOAFERS', hint: 'Slip-on flat casual shoes' },
    { word: 'TRENCH COAT', hint: 'Classic belted rain coat 🧥' },
    { word: 'BLAZER', hint: 'Structured smart formal jacket' },
    { word: 'SUNDRESS', hint: 'Light flowy warm-weather dress ☀️' },
    { word: 'KIMONO', hint: 'Traditional Japanese silk robe' },
    { word: 'SARI', hint: 'Draped colourful South Asian garment 🌺' },
    { word: 'JUMPSUIT', hint: 'One-piece combined top-and-trouser outfit' },
    { word: 'DUNGAREES', hint: 'Bib-front overalls worn casually 👖' },
    { word: 'EYELINER', hint: 'Dark line applied along the eyelid 💄' },
    { word: 'MASCARA', hint: 'Makes your lashes longer and darker 💄' },
    { word: 'BLUSH', hint: 'Pink powder applied to the cheeks 🌸' },
    { word: 'HIGHLIGHTER', hint: 'Shimmery powder for a glowing look ✨' },
    { word: 'MOISTURISER', hint: 'Keeps skin soft and well hydrated 🧴' },
    { word: 'PERFUME', hint: 'Fragrant liquid you spray on 🌸' },
    { word: 'MANICURE', hint: 'Beautifying treatment for nails 💅' },
    { word: 'BRAIDS', hint: 'Plaited strands of hair woven together' },
    { word: 'RUNWAY', hint: 'Fashion show catwalk 👗' },
    { word: 'HANDBAG', hint: 'Carried bag for personal items 👜' },
    { word: 'SCARF', hint: 'Fabric wrapped around neck for style 🧣' },
    { word: 'SUNGLASSES', hint: 'Tinted glasses for sunny days 😎' },
    { word: 'PENDANT', hint: 'Hanging ornament on a necklace' },
    { word: 'FASCINATOR', hint: 'Small decorative hat worn on the head' },
    { word: 'BROCADE', hint: 'Richly decorated ornate woven fabric' },
    { word: 'TAFFETA', hint: 'Crisp and shiny formal fabric' },
    { word: 'CAPSULE', hint: '... wardrobe of essential versatile pieces' },
    { word: 'MONOCHROME', hint: 'Head-to-toe outfit in one colour' },
    { word: 'ANKLET', hint: 'Jewellery delicately worn around the ankle' },
    { word: 'BROOCH', hint: 'Decorative pin worn on clothing' },
    { word: 'BEANIE', hint: 'Close-fitting knitted winter hat 🧢' },
    { word: 'HEADBAND', hint: 'Decorative band worn on the head' },
    { word: 'PALETTE', hint: 'A set of complementary colours 🎨' },
    { word: 'SILHOUETTE', hint: 'The outline shape of an outfit' },
    { word: 'ACCESSORY', hint: 'Finishing touch to complete an outfit' },
    { word: 'EDITORIAL', hint: 'Fashion magazine photo shoot style' },
  ],
  '✈️ Travel & Adventure': [
    { word: 'PASSPORT', hint: 'Your ticket to the whole world 🛂' },
    { word: 'BACKPACKING', hint: 'Travelling light with just a pack 🎒' },
    { word: 'SAFARI', hint: 'African wildlife spotting trip 🦁' },
    { word: 'CRUISE', hint: 'Holiday on a big ocean ship 🚢' },
    { word: 'ROADTRIP', hint: 'Driving across a country with friends 🚗' },
    { word: 'SIGHTSEEING', hint: 'Visiting famous landmarks and sites 📷' },
    { word: 'SOUVENIR', hint: 'A memento to remember your trip' },
    { word: 'ITINERARY', hint: 'A planned travel schedule day-by-day' },
    { word: 'TIMEZONE', hint: 'Different hours in different places 🕐' },
    { word: 'JETLAG', hint: 'Tiredness from crossing time zones 😴' },
    { word: 'EXPEDITION', hint: 'A long organised exploration trip' },
    { word: 'PILGRIMAGE', hint: 'A journey made to a sacred site 🕌' },
    { word: 'NOMAD', hint: 'Someone who has no fixed home 🌍' },
    { word: 'WANDERLUST', hint: 'Strong desire to travel the world' },
    { word: 'EXPLORE', hint: 'To discover unknown and new places' },
    { word: 'GETAWAY', hint: 'A quick short holiday break 🌴' },
    { word: 'HONEYMOON', hint: 'Romantic trip just after a wedding 💑' },
    { word: 'SNORKELING', hint: 'Swimming face-down to see the reef 🐠' },
    { word: 'PARAGLIDING', hint: 'Gliding through air with parachute wing 🪂' },
    { word: 'ZIPLINE', hint: 'Flying through forest on a steel wire' },
    { word: 'KAYAKING', hint: 'Paddling a small lightweight boat 🚣' },
    { word: 'GLAMPING', hint: 'Glamorous and luxury camping 🏕️' },
    { word: 'CULINARY', hint: '... tour to taste local food 🍽️' },
    { word: 'LAYOVER', hint: 'Waiting time between connecting flights' },
    { word: 'DEPARTURE', hint: 'The exciting moment of leaving ✈️' },
    { word: 'ARRIVAL', hint: 'Finally getting to your destination 🙌' },
    { word: 'HITCHHIKE', hint: 'Getting free rides from kind strangers 🚗' },
    { word: 'CHECKPOINT', hint: 'A border crossing inspection point' },
    { word: 'VISA', hint: 'Government permission to enter a country' },
    { word: 'AIRBNB', hint: 'Staying in someone\'s home abroad 🏠' },
    { word: 'HOSTEL', hint: 'Budget dormitory accommodation abroad' },
    { word: 'CAMPERVAN', hint: 'A home on wheels adventure mobile 🚐' },
    { word: 'TREEHOUSE', hint: 'Sleeping in a house built in a tree 🌳' },
    { word: 'BUCKET LIST', hint: 'Things to experience before you die ✅' },
    { word: 'TRANSIT', hint: 'Passing through a place en route' },
    { word: 'CURRENCY', hint: 'Money used in a foreign country 💵' },
    { word: 'LANGUAGE', hint: 'Trying to speak the local tongue 🗣️' },
    { word: 'SUNRISE HIKE', hint: 'Climbing to catch the first light 🌅' },
    { word: 'OVERLAND', hint: 'Travelling continuously across land' },
    { word: 'FESTIVAL', hint: 'Attending a local cultural celebration 🎪' },
    { word: 'PENINSULA', hint: 'A strip of land nearly surrounded by sea' },
    { word: 'BACKROAD', hint: 'A quiet road away from the highway' },
    { word: 'CHECKPOINT', hint: 'A security stop on the border' },
    { word: 'COMPASS', hint: 'A navigation tool pointing north 🧭' },
  ],
};

export const ALL_CATEGORIES = Object.keys(WORD_BANK);
